# Generated by Django 6.1.1 on 2026-09-16 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=2025)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, help_text='Direct link to car image', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('horsepower', models.IntegerField(help_text='Horsepower (HP)')),
                ('zero_to_sixty', models.CharField(default='3.2s', help_text='0-60 mph time', max_length=20)),
                ('top_speed', models.CharField(default='180 mph', max_length=20)),
                ('seats', models.IntegerField(default=5)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Direct-Drive', 'Direct-Drive Dual Motor')], default='Automatic', max_length=30)),
                ('fuel_type', models.CharField(choices=[('Electric', 'Electric'), ('Gasoline', 'Gasoline'), ('Hybrid', 'Hybrid')], default='Electric', max_length=30)),
                ('range_or_economy', models.CharField(default='300 mi range', max_length=50)),
                ('luggage_capacity', models.CharField(default='3 Bags', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('tagline', models.CharField(default='100% Real-Time Availability Guarantee', max_length=255)),
                ('features', models.TextField(blank=True, help_text='Comma-separated features e.g. Autopilot, Premium Audio, Glass Roof')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(default='fa-car', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(editable=False, max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pickup_time', models.CharField(default='10:00 AM', max_length=20)),
                ('pickup_location', models.CharField(default='Downtown Central Hub', max_length=200)),
                ('return_location', models.CharField(default='Downtown Central Hub', max_length=200)),
                ('driver_name', models.CharField(max_length=150)),
                ('driver_email', models.EmailField(max_length=254)),
                ('driver_phone', models.CharField(max_length=30)),
                ('daily_rate_at_booking', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_days', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.IntegerField(default=0)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('insurance_opt', models.BooleanField(default=False)),
                ('chauffeur_opt', models.BooleanField(default=False)),
                ('gps_opt', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='fleet.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='fleet.category'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='fleet.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
