# Generated by Django 6.1.1 on 2026-09-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('license_number', models.CharField(help_text='Commercial Driving License #', max_length=50, unique=True)),
                ('experience_years', models.IntegerField(default=5, help_text='Years of driving experience')),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('trips_completed', models.IntegerField(default=150)),
                ('avatar_url', models.URLField(blank=True, help_text='Direct link to driver profile photo', max_length=500)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('languages', models.CharField(default='English, Hindi', help_text='Languages spoken', max_length=150)),
                ('daily_fee', models.DecimalField(decimal_places=2, default=800.0, help_text='Daily Chauffeur Fee in INR', max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('bio', models.CharField(default='Certified luxury executive chauffeur with clean driving record.', max_length=255)),
                ('badge_type', models.CharField(default='VIP Chauffeur', help_text='e.g. Master Chauffeur, VIP Escort, Track Certified', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='chauffeur_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_license',
            field=models.CharField(blank=True, help_text='Customer Driving License # (For self drive)', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='drive_mode',
            field=models.CharField(choices=[('self', 'Self Drive'), ('chauffeur', 'With Professional Chauffeur')], default='self', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='fleet.driver'),
        ),
    ]
