# Generated by Django 6.1.1 on 2026-09-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_driver_booking_chauffeur_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='avatar_url',
        ),
    ]
